INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('akmeņlauzīte','Saxifraga','saxifrage','Steinbreich','камнеломка','https://en.wikipedia.org/wiki/Saxifraga',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('aronija','Aronia','chokeberry','Apfelbeere','арония','https://en.wikipedia.org/wiki/Aronia',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('āmulis','Viscum','mistletoe','Mistel','омела','https://en.wikipedia.org/wiki/Viscum',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('buksis','Buxus','box','Buchsbaum','самшит','https://en.wikipedia.org/wiki/Buxus',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('ceriņš','Syringa','lilac','Flieder','сирень','https://en.wikipedia.org/wiki/Syringa',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('cinerārija','Cineraria','cineraria','Zinerarie','цинерария','https://en.wikipedia.org/wiki/Cineraria',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('ēdelveiss','Leontopodium','edelweiss','Edelweiß','эдельвейс','https://en.wikipedia.org/wiki/Leontopodium',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('fenhelis','Foeniculum','fennel','Fenchel','фенхель','https://en.wikipedia.org/wiki/Foeniculum',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('floksis','Phlox','phlox','Flammenblume','флокс','https://en.wikipedia.org/wiki/Phlox',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('frēzija','Freesia','freesia','Fresie','фрезия','https://en.wikipedia.org/wiki/Freesia',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('fuksija','Fuchsia','fuchsia','Fuchsie','фуксия','https://en.wikipedia.org/wiki/Fuchsia',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('hiacinte','Hyacinthus','hyacinth','Hyazinthe','гиацинт','https://en.wikipedia.org/wiki/Hyacinth_(plant)',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('kapmirte','Vinca','periwinkle','Immergrün','барвинок','https://en.wikipedia.org/wiki/Vinca',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('kardamonaugs','Elettaria','cardamom','Kardamom','кардамон','https://en.wikipedia.org/wiki/Cardamom',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('kartupelis','Solanum tuberosum','potato','Kartoffel','картофель','https://en.wikipedia.org/wiki/Potato',0);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('kāršroze','Alcea','hollyhock','Stockrose','штокроза','https://en.wikipedia.org/wiki/Alcea',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('kļava','Acer','maple','Ahorn','клен','https://en.wikipedia.org/wiki/Maple',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('ķimene','Carum','caraway','Kümmel','тмин','https://en.wikipedia.org/wiki/Carum',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('ķiploks','Allium sativum','garlic','Knoblauch','чеснок','https://en.wikipedia.org/wiki/Garlic',0);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('lapegle','Larix','larch','Lärche','лиственница','https://en.wikipedia.org/wiki/Larch',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('latvānis','Heracleum','hogweed','Bärenklau','борщевик','https://en.wikipedia.org/wiki/Heracleum_(plant)',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('lauvmutīte','Antirrhinum','snapdragon','Löwenmaul','львиный зев','https://en.wikipedia.org/wiki/Antirrhinum',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('lavanda','Lavandula','lavender','Lavendel','лаванда','https://en.wikipedia.org/wiki/Lavandula',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('lilija','Lilium','lily','Lilie','лилия','https://en.wikipedia.org/wiki/Lilium',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('lobēlija','Lobelia','lobelia','Lobelie','лобелия','https://en.wikipedia.org/wiki/Lobelia',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('mārrutks','Armoracia','horseradish','Meerrettich','хрен','https://en.wikipedia.org/wiki/Horseradish',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('ozols','Quercus','oak','Eiche','дуб','https://en.wikipedia.org/wiki/Oak',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('pastinaks','Pastinaca','parsnip','Pastinak','пастернак','https://en.wikipedia.org/wiki/Pastinaca',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('pētersīlis','Petroselinum','parsley','Petersilie','петрушка',NULL,1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('salvija','Salvia','sage','Salbei','шалфей','https://en.wikipedia.org/wiki/Salvia',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('smaržīgā dille','Anethum graveolens','dill','Dill','пахучий укроп','https://en.wikipedia.org/wiki/Dill',0);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('sniegpulkstenīte','Galanthus','snowdrop','Schneeglöckchen','подснежник','https://en.wikipedia.org/wiki/Galanthus',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('tomāts','Lycopersicon','tomato','Tomate','томат','https://en.wikipedia.org/wiki/Lycopersicon',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('tulpe','Tulipa','Tulip','Tulpe','тюльпан','https://en.wikipedia.org/wiki/Tulip',1);
INSERT INTO translations_table(LATVIAN,LATIN,ENGLISH,GERMAN,RUSSIAN,WIKILINK,IS_GENUS) VALUES ('veronika','Veronica','speedwell','Ehrenpreis','вероника','https://en.wikipedia.org/wiki/Veronica_(plant)',1);
